title: MATLAB_tools
description: Documentation for MATLAB functions to help make figures and run analyses
theme: just-the-docs

url: https://www.campbellmusclelab.org

aux_links:
  Template Repository: https://github.com/campbell-muscle-lab/MATLAB_tools
